### ISSUE TITLE
Geração de Números Aleatórios

### ISSUE THREAD

**Issue by Grund89** [Grund89/Graduar-01-organizador-fila-gem#2]

**Comment by Grund89** [comment]
@Pjmaciel pode dar uma olha se estou no caminho certo do que esta sendo pedido?

**Comment by Pjmaciel** [comment]
Opa Douglas, tudo certo? 

Pelo visto você fez o ambiente do pacote, ja colocou o rspec para os teste, iniciou a classe de estatisticas.


Pontos de atenção;
Você fechou essa Issue de Geraçao de numeros  aleatorios, mas não encontrei no projeto.

na classe  simulador_fila.gemspec
Retire todos os  ¨TODO¨ do arquivo, pois vai ocorrer erros nos seus testes.

Parabéns cara, esta indo muito bem!

**Comment by Grund89** [comment]
Certo Pablo, obrigado pelas dicas.

Coloquei como bloqueado, to quebrando bastante a cabeça por ser algo novo, tbm to levando bastante tempo para compreender o que eh pedido, mas utilizando as ferramentas para avançar.

valeu, tmj...
